### ISSUE TITLE
reduce package size

### ISSUE THREAD

**Issue by jimmywarting** [npm/write-file-atomic#69] opened 2020-07-24 13:22 UTC
Remove `is-typedarray` & `typedarray-to-buffer` to reduce dependencies?

Native solution:
```js
if (ArrayBuffer.isView(arr)) {
  data = Buffer.from(arr.buffer, arr.byteOffset, arr.byteOffset + arr.byteLength)
}
```

Better yet - don't convert it to a buffer. Node v10 supports writing any typedArray with the fs

**Comment by wraithgar** [comment] 2022-01-13 21:05
Duplicate of https://github.com/npm/write-file-atomic/issues/86

**Closed by wraithgar** 2022-01-13 21:05 UTC
