### ISSUE TITLE
Make the temp file hidden

### ISSUE THREAD

**Issue by sindresorhus** [npm/write-file-atomic#30] opened 2017-11-06 05:39 UTC
Currently, it creates a `foo.ext.2343523` temp file of `foo.ext`. When doing an atomic file write in a folder the user might have open in Finder, they will see it and wonder what's happening. It would be nicer if the name of the temp file was prefixed with a `.`, so it would be invisible to the user.

**Comment by iarna** [comment] 2019-01-23 23:30
This doesn't seem unreasonable, per se, though I have mixed feelings.

Pros: Hiding stuff that users shouldn't worry about seems like the right choice.

Neither/nors: `.` files are weird to Windows users, but this just means it should only do this on Mac & Linux where this would actually hide things.

Cons: If a temp file _is_ left over after a run (despite our many efforts to ensure that they aren't), I'm concerned that hiding it may cause more, not less, confusion. Having directories that appear empty but aren't is its own source of support issues.

**Comment by coreyfarrell** [comment] 2019-05-21 13:11
@sindresorhus maybe instead of hiding the file the suffix should include a string to make it clear what is going on, like `foo.ext.tmpfile.234523`?  That way it's not hidden from the user but they're told to ignore it.

**Comment by rgranger** [comment] 2019-07-17 16:44
Hmm...

After looking through the source code in order to understand how this module works (and very nice job btw !), I have been wondering :

Is there a reason for the temporary file to be created in the same folder as the "final" file ?

Wouldn't it be better if the tmp file was created inside the os temporary folder (using `os.tmpdir()`) ?

The problem I see is the following :

If the computer crashes for any reason before the `.rename()`, after the next reboot, the directory that should be containing only "valid" persistant files would also contain the useless temporary file.
Whereas if it was created inside the os temporary folder, that wouldn't be an issue.

**Comment by coreyfarrell** [comment] 2019-07-17 17:23
`fs.rename` cannot be used to move a file to a different mount point or drive:
```
Error: EXDEV: cross-device link not permitted, rename 'testing' -> '/tmp/testing'
```

I'm pretty sure any function that does move files from one device to another would not be atomic, it would create the new file then write the contents.  The problem is that another process might successfully read the destination file while it is still empty or partially written.

**Comment by rgranger** [comment] 2019-07-17 19:00
Seems like a good reason to me.
Thanks for the clarification !

**Comment by wraithgar** [comment] 2022-02-09 20:04
closing due to age.

**Closed by wraithgar** 2022-02-09 20:04 UTC
